config:
  dashboards:
  - name: "Sample Dashboard"
    header: "Sample Dashboard configuration."
    panels:
    - type: "table"
      title: "Deployment versions"
      data_source: "kubernetes"
      api: pods
      query: ""
      namespace: ""
      columns:
      - header: "Name"
        field: "metadata.name"
      - header: "Namespace"
        field: "metadata.namespace"
      - header: "Status"
        field: "status.phase"
      - header: "image"
        field: "spec.containers[0].image"